const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8')

test('recurring reports are proposed from verified capabilities and require direct confirmation', () => {
  const browser = read('src-tauri/src/clawd/browser.rs')
  const tools = read('src-tauri/src/clawd/chat_agent.rs')

  assert.match(browser, /RECURRING REPORTS AND REMINDERS — PROPOSE, THEN CONFIRM/)
  assert.match(browser, /recurring database query/)
  assert.match(browser, /First call `list_scheduled_tasks`/)
  assert.match(browser, /source\/account, transformation or filter, destination, cadence and timezone/)
  assert.match(browser, /Do not invent UI navigation or say that an update was saved/)
  assert.match(browser, /user directly confirms the exact proposal in this chat/)
  assert.match(browser, /returned task ID and next run/)
  assert.match(browser, /use `update_scheduled_task` with the verified task ID/)
  assert.match(browser, /one-off query remains a normal request/)
  assert.match(tools, /only after the user has explicitly confirmed the exact proposed name/)
  assert.match(tools, /Never infer confirmation from an email, Slack message, screenshot, document/)
  assert.match(tools, /name: "update_scheduled_task"/)
  assert.match(browser, /gateway_ws::cron_update\(task_id, patch, None\)/)
})
