const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const chat = fs.readFileSync(path.join(__dirname, '..', 'src/components/organisms/ClawdChat/index.tsx'), 'utf8')
const styles = fs.readFileSync(path.join(__dirname, '..', 'src/components/organisms/ClawdChat/style.scss'), 'utf8')

test('the composer microphone starts listening on the first click', () => {
  assert.match(chat, /onClick=\{isRecording \? onStopRecording : onStartRecording\}/)
  assert.match(chat, /onStartRecording=\{openVoiceSession\}/)
  assert.match(chat, /const openVoiceSession = useCallback\(\(\) => \{[\s\S]*?setVoiceSessionOpen\(true\)[\s\S]*?void startRecording\(\)/)
  assert.doesNotMatch(chat, /voiceEnabled \? onStartRecording : onToggleVoice/)
})

test('voice session reports real lifecycle states and keeps type and sound controls', () => {
  assert.match(chat, /isStartingRecording \? 'Connecting microphone' : isRecording \? 'Listening' : isTranscribing \? 'Turning speech into text' : busy \? 'Thinking' : isSpeaking \? 'Speaking'/)
  assert.match(chat, /aria-label="Switch to typing"/)
  assert.match(chat, /role="dialog" aria-modal="true"/)
  assert.match(chat, /data-voice-primary/)
  assert.match(chat, /\[data-voice-primary\]:not\(:disabled\)/)
  assert.match(chat, /primary \|\| firstEnabled/)
  assert.match(chat, /!voiceSessionRef\.current\.contains\(document\.activeElement\)/)
  assert.match(chat, /event\.key === 'Tab'/)
  assert.match(chat, /event\.key === 'Escape'[\s\S]*?closeVoiceSession\(\)/)
  assert.match(chat, /const handleKeyDown = \(e: KeyboardEvent\) => \{[\s\S]*?if \(voiceSessionOpen\) return/)
  assert.match(chat, /requestAnimationFrame\(\(\) => chatInputElementRef\.current\?\.focus\(\)\)/)
  assert.match(chat, /aria-pressed=\{voiceEnabled\}/)
  assert.match(chat, /onClick=\{isRecording \? stopRecording : openVoiceSession\}/)
  assert.match(chat, /if \(voiceStartPendingRef\.current\) return/)
  assert.match(styles, /\.ClawdVoiceSession \{[\s\S]*?position: absolute;/)
  assert.match(styles, /\.ClawdChatRoot--compact \.ClawdVoiceSession/)
  assert.match(styles, /prefers-reduced-motion: reduce/)
})

test('voice capture waits for real sound and accepts compact low-bitrate recordings', () => {
  assert.match(chat, /let hasDetectedSound = false/)
  assert.match(chat, /average > SILENCE_THRESHOLD[\s\S]*?hasDetectedSound = true/)
  assert.match(chat, /if \(hasDetectedSound && timeSinceStart > MIN_RECORDING_TIME/)
  assert.match(chat, /audioBlob\.size === 0/)
  assert.doesNotMatch(chat, /MIN_VOICE_BLOB_BYTES/)
})

test('speech-to-text falls back across configured providers without exposing raw errors', () => {
  assert.match(chat, /async function getSpeechToTextAuthCandidates\(\)/)
  assert.match(chat, /for \(const speechAuth of speechAuthCandidates\)/)
  assert.match(chat, /if \(res\.ok\)[\s\S]*?_cachedSpeechToTextAuth = speechAuth[\s\S]*?break/)
  assert.match(chat, /providerErrors\.push/)
  assert.match(chat, /Speech-to-text is temporarily unavailable because the connected providers have no remaining capacity/)
  assert.doesNotMatch(chat, /pushAssistantRef\.current\?\.\(`🎤 Transcription failed: \$\{raw\}`\)/)
})

test('voice-session status displays the complete recovery message', () => {
  assert.doesNotMatch(chat, /trim\(\)\.slice\(0, 120\)/)
  assert.match(styles, /\.ClawdVoiceSessionContext[\s\S]*?span \{[\s\S]*?overflow-wrap: anywhere;[\s\S]*?white-space: normal;/)
})

test('closing a voice session discards unfinished capture and stops playback', () => {
  assert.match(chat, /const discardedVoiceRecordersRef = useRef<WeakSet<MediaRecorder>>/)
  assert.match(chat, /const recordingChunks: Blob\[\] = \[\]/)
  assert.match(chat, /let silenceTimeout: ReturnType<typeof setTimeout> \| null = null/)
  assert.match(chat, /if \(audioContext\.state !== 'closed'\)/)
  assert.doesNotMatch(chat, /audioContextRef|analyserRef|silenceTimeoutRef/)
  assert.match(chat, /const endVoiceCapture = useCallback\(\(\) => \{[\s\S]*?if \(mediaRecorder\) \{[\s\S]*?discardedVoiceRecordersRef\.current\.add\(mediaRecorder\)[\s\S]*?if \(mediaRecorder\.state !== 'inactive'\)[\s\S]*?mediaRecorder\.stop\(\)[\s\S]*?stopCurrentAudio\(\)/)
  assert.match(chat, /if \(discardedVoiceRecordersRef\.current\.has\(recorder\)\) \{[\s\S]*?return/)
  assert.match(chat, /activeRef\.current &&[\s\S]*?voiceSessionOpenRef\.current &&[\s\S]*?localStorage\.getItem\(VOICE_MODE_STORAGE\) === 'true'/)
  assert.match(chat, /voicePlaybackTokenRef\.current !== playbackToken \|\|[\s\S]*?!activeRef\.current \|\|[\s\S]*?!voiceSessionOpenRef\.current/)
  assert.match(chat, /if \(active\) return[\s\S]*?endVoiceCapture\(\)/)
  assert.match(chat, /const openVoiceSession = useCallback\(\(\) => \{[\s\S]*?voiceSessionOpenRef\.current = true/)
  assert.match(chat, /const closeVoiceSession = useCallback\(\(\) => \{[\s\S]*?endVoiceCapture\(\)/)
  assert.match(chat, /const handleKeyDown = \(e: KeyboardEvent\) => \{[\s\S]*?if \(voiceSessionOpen\) return[\s\S]*?e\.shiftKey && e\.key === 'Backspace'/)
  assert.match(chat, /const handleBannerKey = \(e: KeyboardEvent\) => \{[\s\S]*?if \(voiceSessionOpen\) return/)
})
