pub const KNAPSACK_STATUS_READHOME_MIN: f32 = 0.0;
pub const KNAPSACK_STATUS_READHOME_MAX: f32 = 0.3;
pub const KNAPSACK_STATUS_SEARCH_MIN: f32 = 0.3;
pub const KNAPSACK_STATUS_SEARCH_MAX: f32 = 0.6;
pub const KNAPSACK_STATUS_SUMMARIZER_MIN: f32 = 0.6;
pub const KNAPSACK_STATUS_SUMMARIZER_MAX: f32 = 1.0;
