export const SAAS_LIST = {
  Salesforce: 'https://salesforce.com',
  Slack: 'https://slack.com',
  Zoom: 'https://zoom.us',
  'Microsoft 365': 'https://microsoft365.com',
  'Google Workspace': 'https://workspace.google.com',
  Asana: 'https://asana.com',
  Dropbox: 'https://dropbox.com',
  HubSpot: 'https://hubspot.com',
  DocuSign: 'https://docusign.com',
  Zendesk: 'https://zendesk.com',
  Atlassian: 'https://atlassian.com',
  ServiceNow: 'https://servicenow.com',
  'Monday.com': 'https://monday.com',
  Notion: 'https://notion.so',
  Trello: 'https://trello.com',
  ClickUp: 'https://clickup.com',
  Miro: 'https://miro.com',
  Airtable: 'https://airtable.com',
  Basecamp: 'https://basecamp.com',
  Confluence: 'https://confluence.com',
  Evernote: 'https://evernote.com',
  'Microsoft Teams': 'https://teams.microsoft.com',
  Box: 'https://box.com',
  Smartsheet: 'https://smartsheet.com',
  Mailchimp: 'https://mailchimp.com',
  'HubSpot Marketing': 'https://hubspot.com/marketing',
  'Google Analytics': 'https://analytics.google.com',
  SEMrush: 'https://semrush.com',
  Hootsuite: 'https://hootsuite.com',
  Buffer: 'https://buffer.com',
  Canva: 'https://canva.com',
  'Adobe Creative Cloud': 'https://adobe.com/creativecloud',
  'Constant Contact': 'https://constantcontact.com',
  Marketo: 'https://marketo.com',
  'Sprout Social': 'https://sproutsocial.com',
  Klaviyo: 'https://klaviyo.com',
  Mixpanel: 'https://mixpanel.com',
  Optimizely: 'https://optimizely.com',
  Unbounce: 'https://unbounce.com',
  SendGrid: 'https://sendgrid.com',
  'Campaign Monitor': 'https://campaignmonitor.com',
  BuzzSumo: 'https://buzzsumo.com',
  Hotjar: 'https://hotjar.com',
  'Crazy Egg': 'https://crazyegg.com',
  Pipedrive: 'https://pipedrive.com',
  'Zoho CRM': 'https://zoho.com/crm',
  Close: 'https://close.com',
  Freshsales: 'https://freshsales.io',
  SalesLoft: 'https://salesloft.com',
  Outreach: 'https://outreach.io',
  Gong: 'https://gong.io',
  Groove: 'https://groove.co',
  Copper: 'https://copper.com',
  'Agile CRM': 'https://agilecrm.com',
  Nimble: 'https://nimble.com',
  ProsperWorks: 'https://prosperworks.com',
  SugarCRM: 'https://sugarcrm.com',
  Vtiger: 'https://vtiger.com',
  Insightly: 'https://insightly.com',
  Capsule: 'https://capsulecrm.com',
  Salesmate: 'https://salesmate.io',
  'Really Simple Systems': 'https://reallysimplesystems.com',
  Bitrix24: 'https://bitrix24.com',
  Streak: 'https://streak.com',
  QuickBooks: 'https://quickbooks.intuit.com',
  Xero: 'https://xero.com',
  FreshBooks: 'https://freshbooks.com',
  Wave: 'https://waveapps.com',
  Sage: 'https://sage.com',
  NetSuite: 'https://netsuite.com',
  'Zoho Books': 'https://zoho.com/books',
  'Bill.com': 'https://bill.com',
  Expensify: 'https://expensify.com',
  'Receipt Bank': 'https://receipt-bank.com',
  Chargebee: 'https://chargebee.com',
  Recurly: 'https://recurly.com',
  Tipalti: 'https://tipalti.com',
  BlackLine: 'https://blackline.com',
  FloQast: 'https://floqast.com',
  Stampli: 'https://stampli.com',
  Divvy: 'https://divvy.com',
  Ramp: 'https://ramp.com',
  Brex: 'https://brex.com',
  Coupa: 'https://coupa.com',
  Workday: 'https://workday.com',
  BambooHR: 'https://bamboohr.com',
  Greenhouse: 'https://greenhouse.io',
  Lever: 'https://lever.co',
  Gusto: 'https://gusto.com',
  'ADP Workforce': 'https://adp.com/workforce',
  'UKG Pro': 'https://ukg.com/pro',
  Paylocity: 'https://paylocity.com',
  'Culture Amp': 'https://cultureamp.com',
  '15Five': 'https://15five.com',
  Lattice: 'https://lattice.com',
  Peakon: 'https://peakon.com',
  Officevibe: 'https://officevibe.com',
  PeopleSoft: 'https://peoplesoft.com',
  Namely: 'https://namely.com',
  Paycor: 'https://paycor.com',
  Rippling: 'https://rippling.com',
  Paycom: 'https://paycom.com',
  Personio: 'https://personio.com',
  Factorial: 'https://factorial.com',
  Intercom: 'https://intercom.com',
  Freshdesk: 'https://freshdesk.com',
  'Help Scout': 'https://helpscout.com',
  Kayako: 'https://kayako.com',
  LiveAgent: 'https://liveagent.com',
  LiveChat: 'https://livechat.com',
  Gladly: 'https://gladly.com',
  Kustomer: 'https://kustomer.com',
  Front: 'https://frontapp.com',
  Drift: 'https://drift.com',
  Talkdesk: 'https://talkdesk.com',
  Five9: 'https://five9.com',
  'Nice inContact': 'https://niceincontact.com',
  'Genesys Cloud': 'https://genesys.com/cloud',
  '8x8': 'https://8x8.com',
  Nextiva: 'https://nextiva.com',
  Dialpad: 'https://dialpad.com',
  Aircall: 'https://aircall.io',
  Gorgias: 'https://gorgias.com',
  GitHub: 'https://github.com',
  GitLab: 'https://gitlab.com',
  Bitbucket: 'https://bitbucket.org',
  'Azure DevOps': 'https://azure.com/devops',
  'New Relic': 'https://newrelic.com',
  Datadog: 'https://datadog.com',
  Dynatrace: 'https://dynatrace.com',
  AppDynamics: 'https://appdynamics.com',
  PagerDuty: 'https://pagerduty.com',
  StatusPage: 'https://statuspage.io',
  Jenkins: 'https://jenkins.io',
  CircleCI: 'https://circleci.com',
  'Travis CI': 'https://travis-ci.org',
  CodeShip: 'https://codeship.com',
  Heroku: 'https://heroku.com',
  DigitalOcean: 'https://digitalocean.com',
  AWS: 'https://aws.amazon.com',
  'Google Cloud Platform': 'https://cloud.google.com',
  'Microsoft Azure': 'https://azure.microsoft.com',
  'Oracle Cloud': 'https://oracle.com/cloud',
  Okta: 'https://okta.com',
  OneLogin: 'https://onelogin.com',
  Auth0: 'https://auth0.com',
  'Duo Security': 'https://duo.com',
  LastPass: 'https://lastpass.com',
  '1Password': 'https://1password.com',
  Dashlane: 'https://dashlane.com',
  Keeper: 'https://keepersecurity.com',
  CrowdStrike: 'https://crowdstrike.com',
  'Carbon Black': 'https://carbonblack.com',
  SentinelOne: 'https://sentinelone.com',
  Rapid7: 'https://rapid7.com',
  Tenable: 'https://tenable.com',
  Qualys: 'https://qualys.com',
  KnowBe4: 'https://knowbe4.com',
  Proofpoint: 'https://proofpoint.com',
  Mimecast: 'https://mimecast.com',
  Zscaler: 'https://zscaler.com',
  Cloudflare: 'https://cloudflare.com',
  Fortinet: 'https://fortinet.com',
  Tableau: 'https://tableau.com',
  'Power BI': 'https://powerbi.microsoft.com',
  Looker: 'https://looker.com',
  Sisense: 'https://sisense.com',
  Qlik: 'https://qlik.com',
  Domo: 'https://domo.com',
  ThoughtSpot: 'https://thoughtspot.com',
  GoodData: 'https://gooddata.com',
  Yellowfin: 'https://yellowfinbi.com',
  Board: 'https://board.com',
  MicroStrategy: 'https://microstrategy.com',
  'SAP Analytics Cloud': 'https://sap.com/analytics-cloud',
  'Oracle Analytics': 'https://oracle.com/analytics',
  SAS: 'https://sas.com',
  Pentaho: 'https://pentaho.com',
  'Zoho Analytics': 'https://zoho.com/analytics',
  Chartio: 'https://chartio.com',
  Grow: 'https://grow.com',
  InsightSquared: 'https://insightsquared.com',
  Klipfolio: 'https://klipfolio.com',
  Shopify: 'https://shopify.com',
  BigCommerce: 'https://bigcommerce.com',
  WooCommerce: 'https://woocommerce.com',
  Magento: 'https://magento.com',
  PrestaShop: 'https://prestashop.com',
  Ecwid: 'https://ecwid.com',
  '3dcart': 'https://3dcart.com',
  Shift4Shop: 'https://shift4shop.com',
  OpenCart: 'https://opencart.com',
  Volusion: 'https://volusion.com',
  AmeriCommerce: 'https://americommerce.com',
  'CS-Cart': 'https://cs-cart.com',
  'X-Cart': 'https://x-cart.com',
  'Salesforce Commerce Cloud': 'https://salesforce.com/commerce-cloud',
  'Oracle Commerce': 'https://oracle.com/commerce',
  'SAP Commerce Cloud': 'https://sap.com/commerce-cloud',
  'Elastic Path': 'https://elasticpath.com',
  commercetools: 'https://commercetools.com',
  'Square Online': 'https://squareup.com/online-store',
  'Wix Stores': 'https://wix.com/stores',
  WordPress: 'https://wordpress.org',
  Drupal: 'https://drupal.org',
  Joomla: 'https://joomla.org',
  Sitecore: 'https://sitecore.com',
  'Adobe Experience Manager': 'https://adobe.com/experience-manager',
  Contentful: 'https://contentful.com',
  Strapi: 'https://strapi.io',
  Ghost: 'https://ghost.org',
  Sanity: 'https://sanity.io',
  Prismic: 'https://prismic.io',
  Contentstack: 'https://contentstack.com',
  Storyblok: 'https://storyblok.com',
  Kentico: 'https://kentico.com',
  Umbraco: 'https://umbraco.com',
  DotCMS: 'https://dotcms.com',
  Magnolia: 'https://magnolia-cms.com',
  Bloomreach: 'https://bloomreach.com',
  Sitefinity: 'https://sitefinity.com',
  Acquia: 'https://acquia.com',
  'Optimizely CMS': 'https://optimizely.com/cms',
  Docebo: 'https://docebo.com',
  TalentLMS: 'https://talentlms.com',
  LearnDash: 'https://learndash.com',
  'Absorb LMS': 'https://absorblms.com',
  iSpring: 'https://ispringsolutions.com',
  'SAP Litmos': 'https://litmos.com',
  Cornerstone: 'https://cornerstoneondemand.com',
  Blackboard: 'https://blackboard.com',
  Canvas: 'https://instructure.com/canvas',
  Moodle: 'https://moodle.org',
  'D2L Brightspace': 'https://d2l.com',
  'Adobe Captivate Prime': 'https://adobe.com/captivate-prime',
  Edmodo: 'https://edmodo.com',
  Schoology: 'https://schoology.com',
  'Google Classroom': 'https://classroom.google.com',
  eFront: 'https://efrontlearning.com',
  'Matrix LMS': 'https://matrixlms.com',
  LearnUpon: 'https://learnupon.com',
  ExpertusONE: 'https://expertus.com',
  'Accord LMS': 'https://accordlms.com',
  Discord: 'https://discord.com',
  'Cisco Webex': 'https://webex.com',
  GoToMeeting: 'https://gotomeeting.com',
  BlueJeans: 'https://bluejeans.com',
  'Join.me': 'https://join.me',
  Whereby: 'https://whereby.com',
  Calendly: 'https://calendly.com',
  ScheduleOnce: 'https://scheduleonce.com',
  'YouCanBook.me': 'https://youcanbook.me',
  Doodle: 'https://doodle.com',
  'x.ai': 'https://x.ai',
  Clara: 'https://clara.com',
  RingCentral: 'https://ringcentral.com',
  Vonage: 'https://vonage.com',
  Grasshopper: 'https://grasshopper.com',
  'Google Voice': 'https://voice.google.com',
  'Zoom Phone': 'https://zoom.us/phone',
  'Microsoft Teams Phone': 'https://teams.microsoft.com/phone',
  Twilio: 'https://twilio.com',
  Plivo: 'https://plivo.com',
}
