// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type AnthropicModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export type KnapsackTierModelOption = {
  id: string
  name: string
  description: string
}

export const ANTHROPIC_MODELS: AnthropicModelOption[] = [
  { id: 'claude-fable-5', name: 'Claude Fable 5', description: 'Anthropic frontier flagship for advanced coding and long-running agentic work', vision: true },
  { id: 'claude-opus-4-8', name: 'Claude Opus 4.8', description: 'Current Opus flagship, excellent for complex coding, reasoning, and vision', vision: true },
  { id: 'claude-opus-4-7', name: 'Claude Opus 4.7', description: 'Earlier Opus release, still excellent for complex tasks', vision: true },
  { id: 'claude-opus-4-6', name: 'Claude Opus 4.6', description: 'Earlier Opus release, still excellent for complex tasks', vision: true },
  { id: 'claude-opus-4-5', name: 'Claude Opus 4.5', description: 'Earlier Opus release, still excellent for complex tasks', vision: true },
  { id: 'claude-opus-4-1', name: 'Claude Opus 4.1', description: 'Earlier Opus release, still excellent for complex tasks', vision: true },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', description: 'Best balance of speed and intelligence for most everyday work', vision: true },
  { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', description: 'Earlier Sonnet release, strong for balanced coding and reasoning', vision: true },
  { id: 'claude-sonnet-4-5', name: 'Claude Sonnet 4.5', description: 'Earlier Sonnet release, strong for balanced coding and reasoning', vision: true },
  { id: 'claude-sonnet-4', name: 'Claude Sonnet 4', description: 'Earlier Sonnet release, strong for balanced coding and reasoning', vision: true },
  { id: 'claude-sonnet-3-7', name: 'Claude Sonnet 3.7', description: 'Earlier Sonnet release, strong for balanced coding and reasoning', vision: true },
  { id: 'claude-sonnet-3-5', name: 'Claude Sonnet 3.5', description: 'Earlier Sonnet release, strong for balanced coding and reasoning', vision: true },
  { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', description: 'Fastest and most affordable Anthropic model', vision: true },
  { id: 'claude-haiku-3-5', name: 'Claude Haiku 3.5', description: 'Earlier Haiku release, optimized for low-latency affordable tasks', vision: true },
]

export const DEFAULT_ANTHROPIC_MODEL = 'claude-opus-4-8'

export const ANTHROPIC_PROVIDER_DESCRIPTION = 'Claude Fable 5, Opus 4.8, Sonnet 5, Haiku 4.5'

export const KNAPSACK_ANTHROPIC_TIER_MODELS: KnapsackTierModelOption[] = [
  { id: 'anthropic/claude-haiku-4-5', name: 'Standard', description: 'Fast, efficient — great for everyday tasks' },
  { id: 'anthropic/claude-sonnet-5', name: 'Plus', description: 'Balanced performance and capability' },
  { id: 'anthropic/claude-opus-4-8', name: 'Premium', description: 'Most powerful — best for complex work' },
]

export const DEFAULT_KNAPSACK_ANTHROPIC_MODEL = 'anthropic/claude-haiku-4-5'
