// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type GeminiModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export const GEMINI_MODELS: GeminiModelOption[] = [
  { id: 'gemini-3.8-flash', name: 'Gemini 3.8 Flash', description: 'Latest fast Gemini model for general work and agent tasks', vision: true },
  { id: 'gemini-3.7-flash', name: 'Gemini 3.7 Flash', description: 'Recent fast Gemini model for general work and agent tasks', vision: true },
  { id: 'gemini-3.6-flash', name: 'Gemini 3.6 Flash', description: 'Recent fast Gemini model for general work and agent tasks', vision: true },
  { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro', description: 'Most capable Gemini reasoning model for complex work', vision: true },
  { id: 'gemini-3.5-flash-lite', name: 'Gemini 3.5 Flash Lite', description: 'Latest cost-efficient Gemini model for high-volume tasks', vision: true },
  { id: 'gemini-3.1-flash-lite', name: 'Gemini 3.1 Flash Lite', description: 'Earlier efficient Gemini model for high-volume tasks', vision: true },
  { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', description: 'Most capable Gemini reasoning model for complex work', vision: true },
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', description: 'Stable, fast, and efficient with thinking', vision: true },
]

export const GEMINI_PROVIDER_DESCRIPTION = 'Gemini 3.8 Flash, 3.7 Flash, 3.6 Flash, 3.1 Pro'
