// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type OpenRouterModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export const OPENROUTER_MODELS: OpenRouterModelOption[] = [
  { id: 'openrouter/auto', name: 'Auto (Smart Routing)', description: 'Automatically picks the best model for each request', vision: true },
  { id: 'qwen/qwen3.8-27b:free', name: 'Qwen 3.8 27B (Free)', description: 'Current free reasoning model with tool use and structured output' },
  { id: 'openai/gpt-5.6-sol', name: 'GPT-5.6 Sol', description: 'OpenAI frontier model for demanding coding and reasoning', vision: true },
  { id: 'anthropic/claude-opus-5.5', name: 'Claude Opus', description: 'Anthropic flagship via OpenRouter', vision: true },
  { id: 'google/gemini-3.8-flash', name: 'Gemini 3.8 Flash', description: 'Google’s newest stable Flash model for agentic work', vision: true },
  { id: 'x-ai/grok-4.7', name: 'Grok 4.7', description: 'xAI flagship for tool calling and agentic work', vision: true },
  { id: 'deepseek/deepseek-v4.1-flash', name: 'DeepSeek V4.1 Flash', description: 'Fast long-context open model for agent loops' },
  { id: 'z-ai/glm-5.3-flash', name: 'GLM 5.3 Flash', description: 'Fast open model for coding and agentic workflows' },
  { id: 'moonshotai/kimi-k3', name: 'Kimi K3', description: 'Moonshot’s current long-context reasoning model' },
  { id: 'minimax/minimax-m3', name: 'MiniMax M3', description: 'Current MiniMax model for coding and autonomous work' },
]

export const DEFAULT_OPENROUTER_MODEL = 'qwen/qwen3.8-27b:free'
