// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type OpenRouterModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export const OPENROUTER_MODELS: OpenRouterModelOption[] = [
  { id: 'openrouter/auto', name: 'Auto (Smart Routing)', description: 'Automatically picks the best model for each request', vision: true },
  { id: 'openai/gpt-oss-120b:free', name: 'GPT-OSS (Free)', description: 'Free open-weight flagship with strong coding and tool use' },
  { id: 'qwen/qwen3-coder:free', name: 'Qwen Coder (Free)', description: 'Free open-source coding model via OpenRouter' },
  { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B (Free)', description: 'Free, versatile general-purpose open model' },
  { id: 'deepseek/deepseek-v4-pro', name: 'DeepSeek V4 Pro (Paid)', description: 'Paid, strong open model for complex reasoning and coding' },
  { id: 'deepseek/deepseek-v4-flash', name: 'DeepSeek V4 Flash (Paid)', description: 'Paid, fast 1M-context variant for agent loops' },
  { id: 'anthropic/claude-opus-4.8', name: 'Claude Opus (Paid)', description: 'Paid Anthropic flagship via OpenRouter', vision: true },
  { id: 'openai/gpt-5.5', name: 'GPT-5 (Paid)', description: 'Paid OpenAI frontier model via OpenRouter', vision: true },
]

export const DEFAULT_OPENROUTER_MODEL = 'openai/gpt-oss-120b:free'
