// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type OpenAIModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export const OPENAI_MODELS: OpenAIModelOption[] = [
  { id: 'gpt-6-astra', name: 'GPT-6 Astra', description: 'Latest agentic model for complex professional work', vision: true },
  { id: 'gpt-6', name: 'GPT-6', description: 'Highly capable general-purpose model', vision: true },
  { id: 'gpt-5.6', name: 'GPT-5.6', description: 'Highly capable general-purpose model', vision: true },
  { id: 'gpt-5.5', name: 'GPT-5.5', description: 'Highly capable general-purpose model', vision: true },
  { id: 'gpt-5.4', name: 'GPT-5.4', description: 'Highly capable general-purpose model', vision: true },
  { id: 'gpt-5', name: 'GPT-5', description: 'Highly capable general-purpose model', vision: true },
  { id: 'gpt-5-mini', name: 'GPT-5 Mini', description: 'Fast and affordable', vision: true },
  { id: 'o3', name: 'o3 (Reasoning)', description: 'Reasoning model for complex logic', vision: true },
]

export const OPENAI_PROVIDER_DESCRIPTION = 'GPT-6 Astra, GPT-6, GPT-5.6, GPT-5.5'
export const DEFAULT_OPENAI_MODEL = 'gpt-5-mini'
