// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type XaiModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export const XAI_MODELS: XaiModelOption[] = [
  { id: 'grok-4.7', name: 'Grok 4.7', description: 'Current xAI flagship for code, tool calling, and general work', vision: true },
  { id: 'grok-build-0.1', name: 'Grok Build 0.1', description: 'Specialized xAI model for agentic coding and web development', vision: true },
  { id: 'grok-4.3', name: 'Grok 4.3', description: 'Prior stable Grok option for compatibility', vision: true },
]
