// AUTO-GENERATED by scripts/refresh-public-provider-models.mjs
// Do not edit this file by hand.

export type XaiModelOption = {
  id: string
  name: string
  description: string
  vision?: boolean
}

export const XAI_MODELS: XaiModelOption[] = [
  { id: 'grok-4.20-beta-latest-reasoning', name: 'Grok 4.20 Reasoning', description: 'Newest Grok reasoning model for complex work', vision: true },
  { id: 'grok-4.20-beta-latest-non-reasoning', name: 'Grok 4.20 Fast', description: 'Fast Grok 4.20 variant for everyday tasks', vision: true },
  { id: 'grok-code-fast-1', name: 'Grok Code Fast 1', description: 'xAI coding model for fast agentic code work' },
  { id: 'grok-4.3-latest', name: 'Grok 4.3', description: 'Latest flagship general-purpose Grok model', vision: true },
  { id: 'grok-4', name: 'Grok 4', description: 'Stable flagship Grok fallback' },
]
